### ISSUE TITLE
Color on CSS property value units

### ISSUE THREAD

**Issue by konradkeska** [prometheux-ar/cyberpunk#54]
I think that putting a color (e.g. orange) on CSS properties value units ("em", "px" etc.) would be great addition to this already awesome theme. I think it would make values more readable.

PS: Maybe vendor-prefixes too? Not sure about that tho.

**Comment by max-SS** [comment]
I like your idea.... as soon as I have time, I will investigate if it is possible in **vsc**... in any case I invite you to do a **PR** if you do not want to wait so long
