### ISSUE TITLE
Separate colors for line numbers and code

### ISSUE THREAD

**Issue by kleinfreund** [prometheux-ar/cyberpunk#60]
The area of the line numbers and the code itself currently have the same color. This creates the impression that the indentation of certain blocks of codes is higher than it actually is.

See the function body in the following screenshot. It is indented by two spaces; however, it sometimes looks like it’s indented by four spaces, especially when the eye rests in the middle of the function body. There, the unindented lines are not in focus and no longer act as a visual anchor.

![Example code displayed with the Cyberpank color theme](https://user-images.githubusercontent.com/5774638/43043729-a7324ea8-8d99-11e8-8842-105498955f34.png)

I propose to use a slightly darker color for the line number area. See Wes Bos’ [Cobalt2](https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2) theme for comparison.

![Example code displayed with the Cobalt2 color theme](https://user-images.githubusercontent.com/5774638/43043743-0b461424-8d9a-11e8-999d-dfa9df86e032.png)

**Comment by max-SS** [comment]
I've been watching, it's not something that supports VSC's api... but, anyway, I'll look into it like the cobalt guys did. :P
