### ISSUE TITLE
UMBRA has dim active file in Explorer when editor is focused

### ISSUE THREAD

**Issue by ryansully** [prometheux-ar/cyberpunk#71]
In the UMBRA theme (both the main theme and SCARLET theme appear to work fine), when focusing the editor area, the active file in the Explorer sidebar becomes dimmed so that the file name can't be read.
<img width="596" alt="screenshot 2018-09-14 14 43 39" src="https://user-images.githubusercontent.com/51629/45576757-60179f00-b82d-11e8-9e48-d7f52961f266.png">

**Comment by ryansully** [comment]
The active file in the screenshot is not in gitignore (the gitignore file itself has the same behavior when it is the active file in Explorer).

**Comment by ryansully** [comment]
For mine I've noticed that normally it appears to be a dark green, but turns a light blue when marked as modified for Git, and red/green for lint errors, so maybe there's a chance that another extension is overriding it? This is only an issue in UMBRA as well; the main theme and SCARLET don't have this issue.

What color should the active Explorer file be? Perhaps I can play around with the theme colors to see if there's a way to fix it. My guess is that there's a theme property being set differently in UMBRA than in main or SCARLET.

**Comment by max-SS** [comment]
It's very strange what happens to you. Here I share the changes of the next update, this should solve the problem (note that these changes are still test and may change). 
```"list.errorForeground": "#ff235a",  
 "list.inactiveSelectionForeground": "#00ff6a", 
 "list.focusBackground": "#002212ec",  
 "list.activeSelectionBackground": "#002212ec",  
 "list.hoverBackground": "#002212ec",
```

Once applied the changes should look like this screenshot.

![image](https://user-images.githubusercontent.com/9059596/45685002-61dbae00-bb1e-11e8-9c47-d49daa9db132.png)

**Comment by ryansully** [comment]
Just tried out those settings in `workbench.colorCustomizations` and they work great! Looking forward to the next release.

**Comment by ryansully** [comment]
I'm gonna close this since it's implemented now.
Thanks again :)
