### ISSUE TITLE
Windows Terminal Spin-Off

### ISSUE THREAD

**Issue by hasparus** [prometheux-ar/cyberpunk#87]
sup! I had a big outrun mood few months ago and as I couldn't find any good cyberpunk theme for Windows Terminal I stole some colors from SCARLET protocol.

I figured out it's time to share.

![image](https://user-images.githubusercontent.com/15332326/73318871-06095500-423b-11ea-9758-02d350bf61f7.png)

[Here's the gist.](https://gist.github.com/hasparus/37f8e6ceb4112a0e33f2223dd1e9dd2e)

**Comment by max-SS** [comment]
Great!!... Thanks for your input and continue to push this "ecosystem" that started with a theme for an editor, and now even has a theme for Chrome. 

Soon I will be adding you in the Cyberpunk README, and in the contributors, as a creator.

**Comment by mikevromen** [comment]
I gave the UMBRA theme a go https://github.com/mikevromen/CyberPunk2077-umbra-WindowsTerminal

**Comment by max-SS** [comment]
Hi, I've added them to the README 🎉 in the spin-off and Hall of Fame sections 😎.
